//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicSubjectDescriptor
    {
        public AcademicSubjectDescriptor()
        {
            this.Assessments = new HashSet<Assessment>();
            this.AssessmentFamilies = new HashSet<AssessmentFamily>();
            this.Cohorts = new HashSet<Cohort>();
            this.Courses = new HashSet<Course>();
            this.CredentialFieldDescriptors = new HashSet<CredentialFieldDescriptor>();
            this.GraduationPlanCreditsBySubjects = new HashSet<GraduationPlanCreditsBySubject>();
            this.LearningObjectives = new HashSet<LearningObjective>();
            this.LearningStandards = new HashSet<LearningStandard>();
            this.OpenStaffPositionAcademicSubjects = new HashSet<OpenStaffPositionAcademicSubject>();
            this.StaffSchoolAssociationAcademicSubjects = new HashSet<StaffSchoolAssociationAcademicSubject>();
        }
    
        public int AcademicSubjectDescriptorId { get; set; }
        public int AcademicSubjectTypeId { get; set; }
    
        public virtual AcademicSubjectType AcademicSubjectType { get; set; }
        public virtual Descriptor Descriptor { get; set; }
        public virtual ICollection<Assessment> Assessments { get; set; }
        public virtual ICollection<AssessmentFamily> AssessmentFamilies { get; set; }
        public virtual ICollection<Cohort> Cohorts { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<CredentialFieldDescriptor> CredentialFieldDescriptors { get; set; }
        public virtual ICollection<GraduationPlanCreditsBySubject> GraduationPlanCreditsBySubjects { get; set; }
        public virtual ICollection<LearningObjective> LearningObjectives { get; set; }
        public virtual ICollection<LearningStandard> LearningStandards { get; set; }
        public virtual ICollection<OpenStaffPositionAcademicSubject> OpenStaffPositionAcademicSubjects { get; set; }
        public virtual ICollection<StaffSchoolAssociationAcademicSubject> StaffSchoolAssociationAcademicSubjects { get; set; }
    }
}
