//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicWeek
    {
        public AcademicWeek()
        {
            this.SessionAcademicWeeks = new HashSet<SessionAcademicWeek>();
        }
    
        public string WeekIdentifier { get; set; }
        public int EducationOrganizationId { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int TotalInstructionalDays { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual CalendarDate CalendarDate { get; set; }
        public virtual CalendarDate CalendarDate1 { get; set; }
        public virtual ICollection<SessionAcademicWeek> SessionAcademicWeeks { get; set; }
    }
}
