//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountCodeDescriptor
    {
        public AccountCodeDescriptor()
        {
            this.AccountCodes = new HashSet<AccountCode>();
        }
    
        public int AccountCodeDescriptorId { get; set; }
        public string AccountCodeCategory { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual ICollection<AccountCode> AccountCodes { get; set; }
        public virtual Descriptor Descriptor { get; set; }
    }
}
