//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccommodationDescriptor
    {
        public AccommodationDescriptor()
        {
            this.StudentAssessmentAccommodations = new HashSet<StudentAssessmentAccommodation>();
        }
    
        public int AccommodationDescriptorId { get; set; }
        public Nullable<int> AccommodationTypeId { get; set; }
    
        public virtual AccommodationType AccommodationType { get; set; }
        public virtual Descriptor Descriptor { get; set; }
        public virtual ICollection<StudentAssessmentAccommodation> StudentAssessmentAccommodations { get; set; }
    }
}
