//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressType
    {
        public AddressType()
        {
            this.EducationOrganizationAddresses = new HashSet<EducationOrganizationAddress>();
            this.EducationOrganizationInternationalAddresses = new HashSet<EducationOrganizationInternationalAddress>();
            this.ParentAddresses = new HashSet<ParentAddress>();
            this.ParentInternationalAddresses = new HashSet<ParentInternationalAddress>();
            this.StaffAddresses = new HashSet<StaffAddress>();
            this.StaffInternationalAddresses = new HashSet<StaffInternationalAddress>();
            this.StudentAddresses = new HashSet<StudentAddress>();
            this.StudentInternationalAddresses = new HashSet<StudentInternationalAddress>();
        }
    
        public int AddressTypeId { get; set; }
        public string CodeValue { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ICollection<EducationOrganizationAddress> EducationOrganizationAddresses { get; set; }
        public virtual ICollection<EducationOrganizationInternationalAddress> EducationOrganizationInternationalAddresses { get; set; }
        public virtual ICollection<ParentAddress> ParentAddresses { get; set; }
        public virtual ICollection<ParentInternationalAddress> ParentInternationalAddresses { get; set; }
        public virtual ICollection<StaffAddress> StaffAddresses { get; set; }
        public virtual ICollection<StaffInternationalAddress> StaffInternationalAddresses { get; set; }
        public virtual ICollection<StudentAddress> StudentAddresses { get; set; }
        public virtual ICollection<StudentInternationalAddress> StudentInternationalAddresses { get; set; }
    }
}
