//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentProgram
    {
        public string AssessmentTitle { get; set; }
        public int AcademicSubjectDescriptorId { get; set; }
        public int AssessedGradeLevelDescriptorId { get; set; }
        public int Version { get; set; }
        public int EducationOrganizationId { get; set; }
        public int ProgramTypeId { get; set; }
        public string ProgramName { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Assessment Assessment { get; set; }
        public virtual Program Program { get; set; }
    }
}
