//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentItem
    {
        public AssessmentItem()
        {
            this.AssessmentItemLearningStandards = new HashSet<AssessmentItemLearningStandard>();
            this.ObjectiveAssessmentAssessmentItems = new HashSet<ObjectiveAssessmentAssessmentItem>();
            this.StudentAssessmentItems = new HashSet<StudentAssessmentItem>();
        }
    
        public string AssessmentTitle { get; set; }
        public int AcademicSubjectDescriptorId { get; set; }
        public int AssessedGradeLevelDescriptorId { get; set; }
        public int Version { get; set; }
        public string IdentificationCode { get; set; }
        public Nullable<int> AssessmentItemCategoryTypeId { get; set; }
        public Nullable<int> MaxRawScore { get; set; }
        public string CorrectResponse { get; set; }
        public string ExpectedTimeAssessed { get; set; }
        public string Nomenclature { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Assessment Assessment { get; set; }
        public virtual AssessmentItemCategoryType AssessmentItemCategoryType { get; set; }
        public virtual ICollection<AssessmentItemLearningStandard> AssessmentItemLearningStandards { get; set; }
        public virtual ICollection<ObjectiveAssessmentAssessmentItem> ObjectiveAssessmentAssessmentItems { get; set; }
        public virtual ICollection<StudentAssessmentItem> StudentAssessmentItems { get; set; }
    }
}
