//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment
    {
        public Assessment()
        {
            this.AssessmentIdentificationCodes = new HashSet<AssessmentIdentificationCode>();
            this.AssessmentItems = new HashSet<AssessmentItem>();
            this.AssessmentLanguages = new HashSet<AssessmentLanguage>();
            this.AssessmentPerformanceLevels = new HashSet<AssessmentPerformanceLevel>();
            this.AssessmentPrograms = new HashSet<AssessmentProgram>();
            this.AssessmentScores = new HashSet<AssessmentScore>();
            this.AssessmentSections = new HashSet<AssessmentSection>();
            this.ObjectiveAssessments = new HashSet<ObjectiveAssessment>();
            this.StudentAssessments = new HashSet<StudentAssessment>();
        }
    
        public string AssessmentTitle { get; set; }
        public int AcademicSubjectDescriptorId { get; set; }
        public int AssessedGradeLevelDescriptorId { get; set; }
        public int Version { get; set; }
        public int AssessmentCategoryTypeId { get; set; }
        public Nullable<int> LowestAssessedGradeLevelDescriptorId { get; set; }
        public string AssessmentForm { get; set; }
        public Nullable<System.DateTime> RevisionDate { get; set; }
        public Nullable<int> MaxRawScore { get; set; }
        public string Nomenclature { get; set; }
        public Nullable<int> AssessmentPeriodDescriptorId { get; set; }
        public string AssessmentFamilyTitle { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual AcademicSubjectDescriptor AcademicSubjectDescriptor { get; set; }
        public virtual GradeLevelDescriptor GradeLevelDescriptor { get; set; }
        public virtual AssessmentCategoryType AssessmentCategoryType { get; set; }
        public virtual AssessmentFamily AssessmentFamily { get; set; }
        public virtual AssessmentPeriodDescriptor AssessmentPeriodDescriptor { get; set; }
        public virtual GradeLevelDescriptor GradeLevelDescriptor1 { get; set; }
        public virtual AssessmentContentStandard AssessmentContentStandard { get; set; }
        public virtual ICollection<AssessmentIdentificationCode> AssessmentIdentificationCodes { get; set; }
        public virtual ICollection<AssessmentItem> AssessmentItems { get; set; }
        public virtual ICollection<AssessmentLanguage> AssessmentLanguages { get; set; }
        public virtual ICollection<AssessmentPerformanceLevel> AssessmentPerformanceLevels { get; set; }
        public virtual ICollection<AssessmentProgram> AssessmentPrograms { get; set; }
        public virtual ICollection<AssessmentScore> AssessmentScores { get; set; }
        public virtual ICollection<AssessmentSection> AssessmentSections { get; set; }
        public virtual ICollection<ObjectiveAssessment> ObjectiveAssessments { get; set; }
        public virtual ICollection<StudentAssessment> StudentAssessments { get; set; }
    }
}
