//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentContentStandardAuthor
    {
        public AssessmentContentStandardAuthor()
        {
    		this.CreateDate = System.DateTime.Now;
        }
    
        public int AssessmentVersion { get; set; }
        public string AssessmentTitle { get; set; }
        public int AcademicSubjectDescriptorId { get; set; }
        public int AssessedGradeLevelDescriptorId { get; set; }
        public string Author { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual AssessmentContentStandard AssessmentContentStandard { get; set; }
    }
}
