//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentPeriodDescriptor
    {
        public AssessmentPeriodDescriptor()
        {
            this.Assessments = new HashSet<Assessment>();
            this.AssessmentFamilyAssessmentPeriods = new HashSet<AssessmentFamilyAssessmentPeriod>();
        }
    
        public int AssessmentPeriodDescriptorId { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual ICollection<Assessment> Assessments { get; set; }
        public virtual ICollection<AssessmentFamilyAssessmentPeriod> AssessmentFamilyAssessmentPeriods { get; set; }
        public virtual Descriptor Descriptor { get; set; }
    }
}
