//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceEventCategoryDescriptor
    {
        public AttendanceEventCategoryDescriptor()
        {
            this.StudentInterventionAttendanceEvents = new HashSet<StudentInterventionAttendanceEvent>();
            this.StudentProgramAttendanceEvents = new HashSet<StudentProgramAttendanceEvent>();
            this.StudentSchoolAttendanceEvents = new HashSet<StudentSchoolAttendanceEvent>();
            this.StudentSectionAttendanceEvents = new HashSet<StudentSectionAttendanceEvent>();
        }
    
        public int AttendanceEventCategoryDescriptorId { get; set; }
        public int AttendanceEventCategoryTypeId { get; set; }
    
        public virtual AttendanceEventCategoryType AttendanceEventCategoryType { get; set; }
        public virtual Descriptor Descriptor { get; set; }
        public virtual ICollection<StudentInterventionAttendanceEvent> StudentInterventionAttendanceEvents { get; set; }
        public virtual ICollection<StudentProgramAttendanceEvent> StudentProgramAttendanceEvents { get; set; }
        public virtual ICollection<StudentSchoolAttendanceEvent> StudentSchoolAttendanceEvents { get; set; }
        public virtual ICollection<StudentSectionAttendanceEvent> StudentSectionAttendanceEvents { get; set; }
    }
}
