//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BehaviorDescriptor
    {
        public BehaviorDescriptor()
        {
            this.DisciplineIncidentBehaviors = new HashSet<DisciplineIncidentBehavior>();
            this.StudentDisciplineIncidentAssociationBehaviors = new HashSet<StudentDisciplineIncidentAssociationBehavior>();
        }
    
        public int BehaviorDescriptorId { get; set; }
        public Nullable<int> BehaviorTypeId { get; set; }
    
        public virtual BehaviorType BehaviorType { get; set; }
        public virtual Descriptor Descriptor { get; set; }
        public virtual ICollection<DisciplineIncidentBehavior> DisciplineIncidentBehaviors { get; set; }
        public virtual ICollection<StudentDisciplineIncidentAssociationBehavior> StudentDisciplineIncidentAssociationBehaviors { get; set; }
    }
}
