//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarDateCalendarEvent
    {
        public CalendarDateCalendarEvent()
        {
    		this.CreateDate = System.DateTime.Now;
        }
    
        public int EducationOrganizationId { get; set; }
        public System.DateTime Date { get; set; }
        public int CalendarEventDescriptorId { get; set; }
        public decimal EventDuration { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CalendarDateCalendarEventIdentity { get; set; }
    
        public virtual CalendarDate CalendarDate { get; set; }
        public virtual CalendarEventDescriptor CalendarEventDescriptor { get; set; }
    }
}
