//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarDate
    {
        public CalendarDate()
        {
            this.AcademicWeeks = new HashSet<AcademicWeek>();
            this.AcademicWeeks1 = new HashSet<AcademicWeek>();
            this.BellSchedules = new HashSet<BellSchedule>();
            this.CalendarDateCalendarEvents = new HashSet<CalendarDateCalendarEvent>();
            this.GradingPeriods = new HashSet<GradingPeriod>();
            this.GradingPeriods1 = new HashSet<GradingPeriod>();
            this.SectionAttendanceTakenEvents = new HashSet<SectionAttendanceTakenEvent>();
        }
    
        public int EducationOrganizationId { get; set; }
        public System.DateTime Date { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ICollection<AcademicWeek> AcademicWeeks { get; set; }
        public virtual ICollection<AcademicWeek> AcademicWeeks1 { get; set; }
        public virtual ICollection<BellSchedule> BellSchedules { get; set; }
        public virtual EducationOrganization EducationOrganization { get; set; }
        public virtual ICollection<CalendarDateCalendarEvent> CalendarDateCalendarEvents { get; set; }
        public virtual ICollection<GradingPeriod> GradingPeriods { get; set; }
        public virtual ICollection<GradingPeriod> GradingPeriods1 { get; set; }
        public virtual ICollection<SectionAttendanceTakenEvent> SectionAttendanceTakenEvents { get; set; }
    }
}
