//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetencyLevelDescriptor
    {
        public CompetencyLevelDescriptor()
        {
            this.CourseCompetencyLevels = new HashSet<CourseCompetencyLevel>();
            this.StudentCompetencyObjectives = new HashSet<StudentCompetencyObjective>();
            this.StudentGradebookEntries = new HashSet<StudentGradebookEntry>();
            this.StudentLearningObjectives = new HashSet<StudentLearningObjective>();
        }
    
        public int CompetencyLevelDescriptorId { get; set; }
        public Nullable<int> PerformanceBaseConversionTypeId { get; set; }
    
        public virtual Descriptor Descriptor { get; set; }
        public virtual PerformanceBaseConversionType PerformanceBaseConversionType { get; set; }
        public virtual ICollection<CourseCompetencyLevel> CourseCompetencyLevels { get; set; }
        public virtual ICollection<StudentCompetencyObjective> StudentCompetencyObjectives { get; set; }
        public virtual ICollection<StudentGradebookEntry> StudentGradebookEntries { get; set; }
        public virtual ICollection<StudentLearningObjective> StudentLearningObjectives { get; set; }
    }
}
