//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContinuationOfServicesReasonDescriptor
    {
        public ContinuationOfServicesReasonDescriptor()
        {
            this.StudentMigrantEducationProgramAssociations = new HashSet<StudentMigrantEducationProgramAssociation>();
        }
    
        public int ContinuationOfServicesReasonDescriptorId { get; set; }
        public int ContinuationOfServicesReasonTypeId { get; set; }
    
        public virtual ContinuationOfServicesReasonType ContinuationOfServicesReasonType { get; set; }
        public virtual Descriptor Descriptor { get; set; }
        public virtual ICollection<StudentMigrantEducationProgramAssociation> StudentMigrantEducationProgramAssociations { get; set; }
    }
}
