//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseTranscript
    {
        public CourseTranscript()
        {
            this.CourseTranscriptAdditionalCredits = new HashSet<CourseTranscriptAdditionalCredit>();
            this.CourseTranscriptExternalCourses = new HashSet<CourseTranscriptExternalCourse>();
        }
    
        public int StudentUSI { get; set; }
        public short SchoolYear { get; set; }
        public int TermTypeId { get; set; }
        public int CourseEducationOrganizationId { get; set; }
        public int EducationOrganizationId { get; set; }
        public string CourseCode { get; set; }
        public int CourseAttemptResultTypeId { get; set; }
        public Nullable<int> AttemptedCreditTypeId { get; set; }
        public Nullable<decimal> AttemptedCreditConversion { get; set; }
        public Nullable<decimal> AttemptedCredit { get; set; }
        public Nullable<int> EarnedCreditTypeId { get; set; }
        public Nullable<decimal> EarnedCreditConversion { get; set; }
        public decimal EarnedCredit { get; set; }
        public Nullable<int> GradeLevelDescriptorId { get; set; }
        public Nullable<int> MethodCreditEarnedTypeId { get; set; }
        public string FinalLetterGradeEarned { get; set; }
        public Nullable<int> FinalNumericGradeEarned { get; set; }
        public Nullable<int> CourseRepeatCodeTypeId { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public string CourseTitle { get; set; }
        public string LocalCourseCode { get; set; }
        public string LocalCourseTitle { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual CourseAttemptResultType CourseAttemptResultType { get; set; }
        public virtual CourseRepeatCodeType CourseRepeatCodeType { get; set; }
        public virtual CreditType CreditType { get; set; }
        public virtual CreditType CreditType1 { get; set; }
        public virtual GradeLevelDescriptor GradeLevelDescriptor { get; set; }
        public virtual MethodCreditEarnedType MethodCreditEarnedType { get; set; }
        public virtual StudentAcademicRecord StudentAcademicRecord { get; set; }
        public virtual ICollection<CourseTranscriptAdditionalCredit> CourseTranscriptAdditionalCredits { get; set; }
        public virtual ICollection<CourseTranscriptExternalCourse> CourseTranscriptExternalCourses { get; set; }
    }
}
