//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditType
    {
        public CreditType()
        {
            this.Courses = new HashSet<Course>();
            this.Courses1 = new HashSet<Course>();
            this.CourseTranscripts = new HashSet<CourseTranscript>();
            this.CourseTranscripts1 = new HashSet<CourseTranscript>();
            this.GraduationPlans = new HashSet<GraduationPlan>();
            this.GraduationPlanCreditsByCourses = new HashSet<GraduationPlanCreditsByCourse>();
            this.GraduationPlanCreditsBySubjects = new HashSet<GraduationPlanCreditsBySubject>();
            this.Sections = new HashSet<Section>();
            this.StudentAcademicRecords = new HashSet<StudentAcademicRecord>();
            this.StudentAcademicRecords1 = new HashSet<StudentAcademicRecord>();
            this.StudentAcademicRecords2 = new HashSet<StudentAcademicRecord>();
            this.StudentAcademicRecords3 = new HashSet<StudentAcademicRecord>();
        }
    
        public int CreditTypeId { get; set; }
        public string CodeValue { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<Course> Courses1 { get; set; }
        public virtual ICollection<CourseTranscript> CourseTranscripts { get; set; }
        public virtual ICollection<CourseTranscript> CourseTranscripts1 { get; set; }
        public virtual ICollection<GraduationPlan> GraduationPlans { get; set; }
        public virtual ICollection<GraduationPlanCreditsByCourse> GraduationPlanCreditsByCourses { get; set; }
        public virtual ICollection<GraduationPlanCreditsBySubject> GraduationPlanCreditsBySubjects { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
        public virtual ICollection<StudentAcademicRecord> StudentAcademicRecords { get; set; }
        public virtual ICollection<StudentAcademicRecord> StudentAcademicRecords1 { get; set; }
        public virtual ICollection<StudentAcademicRecord> StudentAcademicRecords2 { get; set; }
        public virtual ICollection<StudentAcademicRecord> StudentAcademicRecords3 { get; set; }
    }
}
