//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descriptor
    {
        public Descriptor()
        {
    		this.Id = System.Guid.NewGuid();
    		this.LastModifiedDate = System.DateTime.Now;
    		this.CreateDate = System.DateTime.Now;
        }
    
        public int DescriptorId { get; set; }
        public string Namespace { get; set; }
        public string CodeValue { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public Nullable<int> PriorDescriptorId { get; set; }
        public System.DateTime EffectiveBeginDate { get; set; }
        public Nullable<System.DateTime> EffectiveEndDate { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual AcademicSubjectDescriptor AcademicSubjectDescriptor { get; set; }
        public virtual AccommodationDescriptor AccommodationDescriptor { get; set; }
        public virtual AccountCodeDescriptor AccountCodeDescriptor { get; set; }
        public virtual AchievementCategoryDescriptor AchievementCategoryDescriptor { get; set; }
        public virtual AdministrativeFundingControlDescriptor AdministrativeFundingControlDescriptor { get; set; }
        public virtual AssessmentPeriodDescriptor AssessmentPeriodDescriptor { get; set; }
        public virtual AttendanceEventCategoryDescriptor AttendanceEventCategoryDescriptor { get; set; }
        public virtual BehaviorDescriptor BehaviorDescriptor { get; set; }
        public virtual CalendarEventDescriptor CalendarEventDescriptor { get; set; }
        public virtual ClassroomPositionDescriptor ClassroomPositionDescriptor { get; set; }
        public virtual CompetencyLevelDescriptor CompetencyLevelDescriptor { get; set; }
        public virtual ContinuationOfServicesReasonDescriptor ContinuationOfServicesReasonDescriptor { get; set; }
        public virtual CredentialFieldDescriptor CredentialFieldDescriptor { get; set; }
        public virtual DiagnosisDescriptor DiagnosisDescriptor { get; set; }
        public virtual DisabilityDescriptor DisabilityDescriptor { get; set; }
        public virtual DisciplineDescriptor DisciplineDescriptor { get; set; }
        public virtual EmploymentStatusDescriptor EmploymentStatusDescriptor { get; set; }
        public virtual EntryTypeDescriptor EntryTypeDescriptor { get; set; }
        public virtual ExitWithdrawTypeDescriptor ExitWithdrawTypeDescriptor { get; set; }
        public virtual GradeLevelDescriptor GradeLevelDescriptor { get; set; }
        public virtual GradingPeriodDescriptor GradingPeriodDescriptor { get; set; }
        public virtual GraduationPlanTypeDescriptor GraduationPlanTypeDescriptor { get; set; }
        public virtual LanguageDescriptor LanguageDescriptor { get; set; }
        public virtual LevelDescriptor LevelDescriptor { get; set; }
        public virtual LevelOfEducationDescriptor LevelOfEducationDescriptor { get; set; }
        public virtual LimitedEnglishProficiencyDescriptor LimitedEnglishProficiencyDescriptor { get; set; }
        public virtual PerformanceLevelDescriptor PerformanceLevelDescriptor { get; set; }
        public virtual ProgramAssignmentDescriptor ProgramAssignmentDescriptor { get; set; }
        public virtual ProgramCharacteristicDescriptor ProgramCharacteristicDescriptor { get; set; }
        public virtual ReasonExitedDescriptor ReasonExitedDescriptor { get; set; }
        public virtual ReporterDescriptionDescriptor ReporterDescriptionDescriptor { get; set; }
        public virtual ResidencyStatusDescriptor ResidencyStatusDescriptor { get; set; }
        public virtual ResponsibilityDescriptor ResponsibilityDescriptor { get; set; }
        public virtual SchoolFoodServicesEligibilityDescriptor SchoolFoodServicesEligibilityDescriptor { get; set; }
        public virtual SectionCharacteristicDescriptor SectionCharacteristicDescriptor { get; set; }
        public virtual SeparationReasonDescriptor SeparationReasonDescriptor { get; set; }
        public virtual ServiceDescriptor ServiceDescriptor { get; set; }
        public virtual SpecialEducationSettingDescriptor SpecialEducationSettingDescriptor { get; set; }
        public virtual StaffClassificationDescriptor StaffClassificationDescriptor { get; set; }
        public virtual StudentCharacteristicDescriptor StudentCharacteristicDescriptor { get; set; }
        public virtual TeachingCredentialDescriptor TeachingCredentialDescriptor { get; set; }
        public virtual WeaponDescriptor WeaponDescriptor { get; set; }
    }
}
