//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisabilityDescriptor
    {
        public DisabilityDescriptor()
        {
            this.StudentDisabilities = new HashSet<StudentDisability>();
        }
    
        public int DisabilityDescriptorId { get; set; }
        public int DisabilityCategoryTypeId { get; set; }
        public Nullable<int> DisabilityTypeId { get; set; }
    
        public virtual Descriptor Descriptor { get; set; }
        public virtual DisabilityCategoryType DisabilityCategoryType { get; set; }
        public virtual DisabilityType DisabilityType { get; set; }
        public virtual ICollection<StudentDisability> StudentDisabilities { get; set; }
    }
}
