//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisciplineDescriptor
    {
        public DisciplineDescriptor()
        {
            this.DisciplineActionDisciplines = new HashSet<DisciplineActionDiscipline>();
        }
    
        public int DisciplineDescriptorId { get; set; }
        public Nullable<int> DisciplineTypeId { get; set; }
    
        public virtual Descriptor Descriptor { get; set; }
        public virtual ICollection<DisciplineActionDiscipline> DisciplineActionDisciplines { get; set; }
        public virtual DisciplineType DisciplineType { get; set; }
    }
}
