//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisciplineIncident
    {
        public DisciplineIncident()
        {
    		this.Id = System.Guid.NewGuid();
    		this.LastModifiedDate = System.DateTime.Now;
    		this.CreateDate = System.DateTime.Now;
            this.DisciplineActionDisciplineIncidents = new HashSet<DisciplineActionDisciplineIncident>();
            this.DisciplineIncidentBehaviors = new HashSet<DisciplineIncidentBehavior>();
            this.DisciplineIncidentWeapons = new HashSet<DisciplineIncidentWeapon>();
            this.StudentDisciplineIncidentAssociations = new HashSet<StudentDisciplineIncidentAssociation>();
        }
    
        public int SchoolId { get; set; }
        public string IncidentIdentifier { get; set; }
        public System.DateTime IncidentDate { get; set; }
        public Nullable<System.TimeSpan> IncidentTime { get; set; }
        public Nullable<int> IncidentLocationTypeId { get; set; }
        public Nullable<int> ReporterDescriptionDescriptorId { get; set; }
        public string ReporterName { get; set; }
        public Nullable<bool> ReportedToLawEnforcement { get; set; }
        public string CaseNumber { get; set; }
        public Nullable<int> StaffUSI { get; set; }
        public Nullable<decimal> IncidentCost { get; set; }
        public string IncidentDescription { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ICollection<DisciplineActionDisciplineIncident> DisciplineActionDisciplineIncidents { get; set; }
        public virtual IncidentLocationType IncidentLocationType { get; set; }
        public virtual ReporterDescriptionDescriptor ReporterDescriptionDescriptor { get; set; }
        public virtual School School { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual ICollection<DisciplineIncidentBehavior> DisciplineIncidentBehaviors { get; set; }
        public virtual ICollection<DisciplineIncidentWeapon> DisciplineIncidentWeapons { get; set; }
        public virtual ICollection<StudentDisciplineIncidentAssociation> StudentDisciplineIncidentAssociations { get; set; }
    }
}
