//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisciplineAction
    {
        public DisciplineAction()
        {
            this.DisciplineActionDisciplines = new HashSet<DisciplineActionDiscipline>();
            this.DisciplineActionDisciplineIncidents = new HashSet<DisciplineActionDisciplineIncident>();
            this.DisciplineActionStaffs = new HashSet<DisciplineActionStaff>();
        }
    
        public int StudentUSI { get; set; }
        public string DisciplineActionIdentifier { get; set; }
        public System.DateTime DisciplineDate { get; set; }
        public Nullable<int> DisciplineActionLength { get; set; }
        public Nullable<int> ActualDisciplineActionLength { get; set; }
        public Nullable<int> DisciplineActionLengthDifferenceReasonTypeId { get; set; }
        public int ResponsibilitySchoolId { get; set; }
        public Nullable<int> AssignmentSchoolId { get; set; }
        public Nullable<bool> RelatedToZeroTolerancePolicy { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual DisciplineActionLengthDifferenceReasonType DisciplineActionLengthDifferenceReasonType { get; set; }
        public virtual School School { get; set; }
        public virtual School School1 { get; set; }
        public virtual Student Student { get; set; }
        public virtual ICollection<DisciplineActionDiscipline> DisciplineActionDisciplines { get; set; }
        public virtual ICollection<DisciplineActionDisciplineIncident> DisciplineActionDisciplineIncidents { get; set; }
        public virtual ICollection<DisciplineActionStaff> DisciplineActionStaffs { get; set; }
    }
}
