//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationContent
    {
        public EducationContent()
        {
    		this.Id = System.Guid.NewGuid();
    		this.LastModifiedDate = System.DateTime.Now;
    		this.CreateDate = System.DateTime.Now;
            this.EducationContentAppropriateGradeLevels = new HashSet<EducationContentAppropriateGradeLevel>();
            this.EducationContentAppropriateSexes = new HashSet<EducationContentAppropriateSex>();
            this.EducationContentAuthors = new HashSet<EducationContentAuthor>();
            this.EducationContentDerivativeSourceEducationContents = new HashSet<EducationContentDerivativeSourceEducationContent>();
            this.EducationContentDerivativeSourceEducationContents1 = new HashSet<EducationContentDerivativeSourceEducationContent>();
            this.EducationContentDerivativeSourceLearningResourceMetadataURIs = new HashSet<EducationContentDerivativeSourceLearningResourceMetadataURI>();
            this.EducationContentDerivativeSourceURIs = new HashSet<EducationContentDerivativeSourceURI>();
            this.EducationContentLanguages = new HashSet<EducationContentLanguage>();
            this.InterventionEducationContents = new HashSet<InterventionEducationContent>();
            this.InterventionPrescriptionEducationContents = new HashSet<InterventionPrescriptionEducationContent>();
            this.InterventionStudyEducationContents = new HashSet<InterventionStudyEducationContent>();
        }
    
        public string ContentIdentifier { get; set; }
        public string LearningResourceMetadataURI { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public Nullable<bool> AdditionalAuthorsIndicator { get; set; }
        public string Publisher { get; set; }
        public string TimeRequired { get; set; }
        public Nullable<int> InteractivityStyleTypeId { get; set; }
        public Nullable<int> ContentClassTypeId { get; set; }
        public string UseRightsURL { get; set; }
        public Nullable<System.DateTime> PublicationDate { get; set; }
        public Nullable<short> PublicationYear { get; set; }
        public string LearningStandardId { get; set; }
        public string Version { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> CostRateTypeId { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int EducationContentIdentity { get; set; }
    
        public virtual ContentClassType ContentClassType { get; set; }
        public virtual CostRateType CostRateType { get; set; }
        public virtual InteractivityStyleType InteractivityStyleType { get; set; }
        public virtual LearningStandard LearningStandard { get; set; }
        public virtual ICollection<EducationContentAppropriateGradeLevel> EducationContentAppropriateGradeLevels { get; set; }
        public virtual ICollection<EducationContentAppropriateSex> EducationContentAppropriateSexes { get; set; }
        public virtual ICollection<EducationContentAuthor> EducationContentAuthors { get; set; }
        public virtual ICollection<EducationContentDerivativeSourceEducationContent> EducationContentDerivativeSourceEducationContents { get; set; }
        public virtual ICollection<EducationContentDerivativeSourceEducationContent> EducationContentDerivativeSourceEducationContents1 { get; set; }
        public virtual ICollection<EducationContentDerivativeSourceLearningResourceMetadataURI> EducationContentDerivativeSourceLearningResourceMetadataURIs { get; set; }
        public virtual ICollection<EducationContentDerivativeSourceURI> EducationContentDerivativeSourceURIs { get; set; }
        public virtual ICollection<EducationContentLanguage> EducationContentLanguages { get; set; }
        public virtual ICollection<InterventionEducationContent> InterventionEducationContents { get; set; }
        public virtual ICollection<InterventionPrescriptionEducationContent> InterventionPrescriptionEducationContents { get; set; }
        public virtual ICollection<InterventionStudyEducationContent> InterventionStudyEducationContents { get; set; }
    }
}
