//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationOrganizationNetwork
    {
        public EducationOrganizationNetwork()
        {
            this.EducationOrganizationNetworkAssociations = new HashSet<EducationOrganizationNetworkAssociation>();
        }
    
        public int EducationOrganizationNetworkId { get; set; }
        public int NetworkPurposeTypeId { get; set; }
        public int EducationOrganizationNetworkIdentity { get; set; }
    
        public virtual EducationOrganization EducationOrganization { get; set; }
        public virtual NetworkPurposeType NetworkPurposeType { get; set; }
        public virtual ICollection<EducationOrganizationNetworkAssociation> EducationOrganizationNetworkAssociations { get; set; }
    }
}
