//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectronicMailType
    {
        public ElectronicMailType()
        {
    		this.Id = System.Guid.NewGuid();
    		this.LastModifiedDate = System.DateTime.Now;
    		this.CreateDate = System.DateTime.Now;
            this.ParentElectronicMails = new HashSet<ParentElectronicMail>();
            this.StaffElectronicMails = new HashSet<StaffElectronicMail>();
            this.StudentElectronicMails = new HashSet<StudentElectronicMail>();
        }
    
        public int ElectronicMailTypeId { get; set; }
        public string CodeValue { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ICollection<ParentElectronicMail> ParentElectronicMails { get; set; }
        public virtual ICollection<StaffElectronicMail> StaffElectronicMails { get; set; }
        public virtual ICollection<StudentElectronicMail> StudentElectronicMails { get; set; }
    }
}
