//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploymentStatusDescriptor
    {
        public EmploymentStatusDescriptor()
        {
            this.OpenStaffPositions = new HashSet<OpenStaffPosition>();
            this.StaffEducationOrganizationEmploymentAssociations = new HashSet<StaffEducationOrganizationEmploymentAssociation>();
        }
    
        public int EmploymentStatusDescriptorId { get; set; }
        public int EmploymentStatusTypeId { get; set; }
    
        public virtual Descriptor Descriptor { get; set; }
        public virtual EmploymentStatusType EmploymentStatusType { get; set; }
        public virtual ICollection<OpenStaffPosition> OpenStaffPositions { get; set; }
        public virtual ICollection<StaffEducationOrganizationEmploymentAssociation> StaffEducationOrganizationEmploymentAssociations { get; set; }
    }
}
