//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExitWithdrawTypeDescriptor
    {
        public ExitWithdrawTypeDescriptor()
        {
            this.StudentSchoolAssociations = new HashSet<StudentSchoolAssociation>();
        }
    
        public int ExitWithdrawTypeDescriptorId { get; set; }
        public Nullable<int> ExitWithdrawTypeId { get; set; }
    
        public virtual Descriptor Descriptor { get; set; }
        public virtual ExitWithdrawType ExitWithdrawType { get; set; }
        public virtual ICollection<StudentSchoolAssociation> StudentSchoolAssociations { get; set; }
    }
}
