//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraduationPlanCreditsByCourse
    {
        public GraduationPlanCreditsByCourse()
        {
    		this.CreateDate = System.DateTime.Now;
            this.GraduationPlanCreditsByCourseCourses = new HashSet<GraduationPlanCreditsByCourseCourse>();
        }
    
        public int EducationOrganizationId { get; set; }
        public decimal Credit { get; set; }
        public Nullable<int> CreditTypeId { get; set; }
        public Nullable<decimal> CreditConversion { get; set; }
        public Nullable<int> GradeLevelDescriptorId { get; set; }
        public int GraduationPlanTypeDescriptorId { get; set; }
        public short GraduationSchoolYear { get; set; }
        public string CourseSetName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int GraduationPlanCreditsByCourseIdentity { get; set; }
    
        public virtual CreditType CreditType { get; set; }
        public virtual GradeLevelDescriptor GradeLevelDescriptor { get; set; }
        public virtual GraduationPlan GraduationPlan { get; set; }
        public virtual ICollection<GraduationPlanCreditsByCourseCourse> GraduationPlanCreditsByCourseCourses { get; set; }
    }
}
