//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradingPeriodDescriptor
    {
        public GradingPeriodDescriptor()
        {
            this.GradingPeriods = new HashSet<GradingPeriod>();
        }
    
        public int GradingPeriodDescriptorId { get; set; }
        public int GradingPeriodTypeId { get; set; }
    
        public virtual Descriptor Descriptor { get; set; }
        public virtual ICollection<GradingPeriod> GradingPeriods { get; set; }
        public virtual GradingPeriodType GradingPeriodType { get; set; }
    }
}
