//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int StudentUSI { get; set; }
        public int SchoolId { get; set; }
        public string ClassPeriodName { get; set; }
        public string ClassroomIdentificationCode { get; set; }
        public string LocalCourseCode { get; set; }
        public int TermTypeId { get; set; }
        public short SchoolYear { get; set; }
        public System.DateTime BeginDate { get; set; }
        public int GradingPeriodDescriptorId { get; set; }
        public System.DateTime GradingPeriodBeginDate { get; set; }
        public int GradingPeriodEducationOrganizationId { get; set; }
        public string LetterGradeEarned { get; set; }
        public Nullable<int> NumericGradeEarned { get; set; }
        public string DiagnosticStatement { get; set; }
        public int GradeTypeId { get; set; }
        public Nullable<int> PerformanceBaseConversionTypeId { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual GradeType GradeType { get; set; }
        public virtual GradingPeriod GradingPeriod { get; set; }
        public virtual PerformanceBaseConversionType PerformanceBaseConversionType { get; set; }
        public virtual StudentSectionAssociation StudentSectionAssociation { get; set; }
        public virtual ReportCardGrade ReportCardGrade { get; set; }
    }
}
