//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradingPeriod
    {
        public GradingPeriod()
        {
            this.Grades = new HashSet<Grade>();
            this.GradebookEntries = new HashSet<GradebookEntry>();
            this.ReportCards = new HashSet<ReportCard>();
            this.SessionGradingPeriods = new HashSet<SessionGradingPeriod>();
            this.StudentCompetencyObjectives = new HashSet<StudentCompetencyObjective>();
            this.StudentLearningObjectives = new HashSet<StudentLearningObjective>();
        }
    
        public int EducationOrganizationId { get; set; }
        public int GradingPeriodDescriptorId { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int TotalInstructionalDays { get; set; }
        public Nullable<int> PeriodSequence { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual CalendarDate CalendarDate { get; set; }
        public virtual CalendarDate CalendarDate1 { get; set; }
        public virtual ICollection<Grade> Grades { get; set; }
        public virtual ICollection<GradebookEntry> GradebookEntries { get; set; }
        public virtual GradingPeriodDescriptor GradingPeriodDescriptor { get; set; }
        public virtual ICollection<ReportCard> ReportCards { get; set; }
        public virtual ICollection<SessionGradingPeriod> SessionGradingPeriods { get; set; }
        public virtual ICollection<StudentCompetencyObjective> StudentCompetencyObjectives { get; set; }
        public virtual ICollection<StudentLearningObjective> StudentLearningObjectives { get; set; }
    }
}
