//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeLevelDescriptor
    {
        public GradeLevelDescriptor()
        {
            this.Assessments = new HashSet<Assessment>();
            this.Assessments1 = new HashSet<Assessment>();
            this.AssessmentFamilies = new HashSet<AssessmentFamily>();
            this.AssessmentFamilies1 = new HashSet<AssessmentFamily>();
            this.BellSchedules = new HashSet<BellSchedule>();
            this.CompetencyObjectives = new HashSet<CompetencyObjective>();
            this.CourseGradeLevels = new HashSet<CourseGradeLevel>();
            this.CourseTranscripts = new HashSet<CourseTranscript>();
            this.EducationContentAppropriateGradeLevels = new HashSet<EducationContentAppropriateGradeLevel>();
            this.GraduationPlanCreditsByCourses = new HashSet<GraduationPlanCreditsByCourse>();
            this.InterventionAppropriateGradeLevels = new HashSet<InterventionAppropriateGradeLevel>();
            this.InterventionPrescriptionAppropriateGradeLevels = new HashSet<InterventionPrescriptionAppropriateGradeLevel>();
            this.InterventionStudyAppropriateGradeLevels = new HashSet<InterventionStudyAppropriateGradeLevel>();
            this.InterventionStudyInterventionEffectivenesses = new HashSet<InterventionStudyInterventionEffectiveness>();
            this.LearningObjectives = new HashSet<LearningObjective>();
            this.LearningStandards = new HashSet<LearningStandard>();
            this.LevelDescriptorGradeLevels = new HashSet<LevelDescriptorGradeLevel>();
            this.OpenStaffPositionInstructionalGradeLevels = new HashSet<OpenStaffPositionInstructionalGradeLevel>();
            this.SchoolGradeLevels = new HashSet<SchoolGradeLevel>();
            this.StaffSchoolAssociationGradeLevels = new HashSet<StaffSchoolAssociationGradeLevel>();
            this.StudentAssessments = new HashSet<StudentAssessment>();
            this.StudentInterventionAssociationInterventionEffectivenesses = new HashSet<StudentInterventionAssociationInterventionEffectiveness>();
            this.StudentSchoolAssociations = new HashSet<StudentSchoolAssociation>();
        }
    
        public int GradeLevelDescriptorId { get; set; }
        public int GradeLevelTypeId { get; set; }
    
        public virtual ICollection<Assessment> Assessments { get; set; }
        public virtual ICollection<Assessment> Assessments1 { get; set; }
        public virtual ICollection<AssessmentFamily> AssessmentFamilies { get; set; }
        public virtual ICollection<AssessmentFamily> AssessmentFamilies1 { get; set; }
        public virtual ICollection<BellSchedule> BellSchedules { get; set; }
        public virtual ICollection<CompetencyObjective> CompetencyObjectives { get; set; }
        public virtual ICollection<CourseGradeLevel> CourseGradeLevels { get; set; }
        public virtual ICollection<CourseTranscript> CourseTranscripts { get; set; }
        public virtual Descriptor Descriptor { get; set; }
        public virtual ICollection<EducationContentAppropriateGradeLevel> EducationContentAppropriateGradeLevels { get; set; }
        public virtual GradeLevelType GradeLevelType { get; set; }
        public virtual ICollection<GraduationPlanCreditsByCourse> GraduationPlanCreditsByCourses { get; set; }
        public virtual ICollection<InterventionAppropriateGradeLevel> InterventionAppropriateGradeLevels { get; set; }
        public virtual ICollection<InterventionPrescriptionAppropriateGradeLevel> InterventionPrescriptionAppropriateGradeLevels { get; set; }
        public virtual ICollection<InterventionStudyAppropriateGradeLevel> InterventionStudyAppropriateGradeLevels { get; set; }
        public virtual ICollection<InterventionStudyInterventionEffectiveness> InterventionStudyInterventionEffectivenesses { get; set; }
        public virtual ICollection<LearningObjective> LearningObjectives { get; set; }
        public virtual ICollection<LearningStandard> LearningStandards { get; set; }
        public virtual ICollection<LevelDescriptorGradeLevel> LevelDescriptorGradeLevels { get; set; }
        public virtual ICollection<OpenStaffPositionInstructionalGradeLevel> OpenStaffPositionInstructionalGradeLevels { get; set; }
        public virtual ICollection<SchoolGradeLevel> SchoolGradeLevels { get; set; }
        public virtual ICollection<StaffSchoolAssociationGradeLevel> StaffSchoolAssociationGradeLevels { get; set; }
        public virtual ICollection<StudentAssessment> StudentAssessments { get; set; }
        public virtual ICollection<StudentInterventionAssociationInterventionEffectiveness> StudentInterventionAssociationInterventionEffectivenesses { get; set; }
        public virtual ICollection<StudentSchoolAssociation> StudentSchoolAssociations { get; set; }
    }
}
