//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intervention
    {
        public Intervention()
        {
    		this.Id = System.Guid.NewGuid();
    		this.LastModifiedDate = System.DateTime.Now;
    		this.CreateDate = System.DateTime.Now;
            this.InterventionAppropriateGradeLevels = new HashSet<InterventionAppropriateGradeLevel>();
            this.InterventionAppropriateSexes = new HashSet<InterventionAppropriateSex>();
            this.InterventionDiagnosis = new HashSet<InterventionDiagnosi>();
            this.InterventionEducationContents = new HashSet<InterventionEducationContent>();
            this.InterventionInterventionPrescriptions = new HashSet<InterventionInterventionPrescription>();
            this.InterventionLearningResourceMetadataURIs = new HashSet<InterventionLearningResourceMetadataURI>();
            this.InterventionMeetingTimes = new HashSet<InterventionMeetingTime>();
            this.InterventionPopulationServeds = new HashSet<InterventionPopulationServed>();
            this.InterventionStaffs = new HashSet<InterventionStaff>();
            this.InterventionURIs = new HashSet<InterventionURI>();
            this.StudentInterventionAssociations = new HashSet<StudentInterventionAssociation>();
            this.StudentInterventionAttendanceEvents = new HashSet<StudentInterventionAttendanceEvent>();
        }
    
        public string InterventionIdentificationCode { get; set; }
        public int InterventionClassTypeId { get; set; }
        public int DeliveryMethodTypeId { get; set; }
        public int EducationOrganizationId { get; set; }
        public System.DateTime BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int InterventionIdentity { get; set; }
    
        public virtual DeliveryMethodType DeliveryMethodType { get; set; }
        public virtual EducationOrganization EducationOrganization { get; set; }
        public virtual InterventionClassType InterventionClassType { get; set; }
        public virtual ICollection<InterventionAppropriateGradeLevel> InterventionAppropriateGradeLevels { get; set; }
        public virtual ICollection<InterventionAppropriateSex> InterventionAppropriateSexes { get; set; }
        public virtual ICollection<InterventionDiagnosi> InterventionDiagnosis { get; set; }
        public virtual ICollection<InterventionEducationContent> InterventionEducationContents { get; set; }
        public virtual ICollection<InterventionInterventionPrescription> InterventionInterventionPrescriptions { get; set; }
        public virtual ICollection<InterventionLearningResourceMetadataURI> InterventionLearningResourceMetadataURIs { get; set; }
        public virtual ICollection<InterventionMeetingTime> InterventionMeetingTimes { get; set; }
        public virtual ICollection<InterventionPopulationServed> InterventionPopulationServeds { get; set; }
        public virtual ICollection<InterventionStaff> InterventionStaffs { get; set; }
        public virtual ICollection<InterventionURI> InterventionURIs { get; set; }
        public virtual ICollection<StudentInterventionAssociation> StudentInterventionAssociations { get; set; }
        public virtual ICollection<StudentInterventionAttendanceEvent> StudentInterventionAttendanceEvents { get; set; }
    }
}
