//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterventionPrescription
    {
        public InterventionPrescription()
        {
    		this.Id = System.Guid.NewGuid();
    		this.LastModifiedDate = System.DateTime.Now;
    		this.CreateDate = System.DateTime.Now;
            this.EducationOrganizationInterventionPrescriptionAssociations = new HashSet<EducationOrganizationInterventionPrescriptionAssociation>();
            this.InterventionInterventionPrescriptions = new HashSet<InterventionInterventionPrescription>();
            this.InterventionPrescriptionAppropriateGradeLevels = new HashSet<InterventionPrescriptionAppropriateGradeLevel>();
            this.InterventionPrescriptionAppropriateSexes = new HashSet<InterventionPrescriptionAppropriateSex>();
            this.InterventionPrescriptionDiagnosis = new HashSet<InterventionPrescriptionDiagnosi>();
            this.InterventionPrescriptionEducationContents = new HashSet<InterventionPrescriptionEducationContent>();
            this.InterventionPrescriptionLearningResourceMetadataURIs = new HashSet<InterventionPrescriptionLearningResourceMetadataURI>();
            this.InterventionPrescriptionPopulationServeds = new HashSet<InterventionPrescriptionPopulationServed>();
            this.InterventionPrescriptionURIs = new HashSet<InterventionPrescriptionURI>();
            this.InterventionStudies = new HashSet<InterventionStudy>();
        }
    
        public string InterventionPrescriptionIdentificationCode { get; set; }
        public int EducationOrganizationId { get; set; }
        public int InterventionClassTypeId { get; set; }
        public int DeliveryMethodTypeId { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int InterventionPrescriptionIdentity { get; set; }
    
        public virtual DeliveryMethodType DeliveryMethodType { get; set; }
        public virtual EducationOrganization EducationOrganization { get; set; }
        public virtual ICollection<EducationOrganizationInterventionPrescriptionAssociation> EducationOrganizationInterventionPrescriptionAssociations { get; set; }
        public virtual InterventionClassType InterventionClassType { get; set; }
        public virtual ICollection<InterventionInterventionPrescription> InterventionInterventionPrescriptions { get; set; }
        public virtual ICollection<InterventionPrescriptionAppropriateGradeLevel> InterventionPrescriptionAppropriateGradeLevels { get; set; }
        public virtual ICollection<InterventionPrescriptionAppropriateSex> InterventionPrescriptionAppropriateSexes { get; set; }
        public virtual ICollection<InterventionPrescriptionDiagnosi> InterventionPrescriptionDiagnosis { get; set; }
        public virtual ICollection<InterventionPrescriptionEducationContent> InterventionPrescriptionEducationContents { get; set; }
        public virtual ICollection<InterventionPrescriptionLearningResourceMetadataURI> InterventionPrescriptionLearningResourceMetadataURIs { get; set; }
        public virtual ICollection<InterventionPrescriptionPopulationServed> InterventionPrescriptionPopulationServeds { get; set; }
        public virtual ICollection<InterventionPrescriptionURI> InterventionPrescriptionURIs { get; set; }
        public virtual ICollection<InterventionStudy> InterventionStudies { get; set; }
    }
}
