//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterventionStudy
    {
        public InterventionStudy()
        {
    		this.Id = System.Guid.NewGuid();
    		this.LastModifiedDate = System.DateTime.Now;
    		this.CreateDate = System.DateTime.Now;
            this.InterventionStudyAppropriateGradeLevels = new HashSet<InterventionStudyAppropriateGradeLevel>();
            this.InterventionStudyAppropriateSexes = new HashSet<InterventionStudyAppropriateSex>();
            this.InterventionStudyEducationContents = new HashSet<InterventionStudyEducationContent>();
            this.InterventionStudyInterventionEffectivenesses = new HashSet<InterventionStudyInterventionEffectiveness>();
            this.InterventionStudyLearningResourceMetadataURIs = new HashSet<InterventionStudyLearningResourceMetadataURI>();
            this.InterventionStudyPopulationServeds = new HashSet<InterventionStudyPopulationServed>();
            this.InterventionStudyStateAbbreviations = new HashSet<InterventionStudyStateAbbreviation>();
            this.InterventionStudyURIs = new HashSet<InterventionStudyURI>();
        }
    
        public string InterventionStudyIdentificationCode { get; set; }
        public int EducationOrganizationId { get; set; }
        public string InterventionPrescriptionIdentificationCode { get; set; }
        public int InterventionPrescriptionEducationOrganizationId { get; set; }
        public int Participants { get; set; }
        public int DeliveryMethodTypeId { get; set; }
        public int InterventionClassTypeId { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int InterventionStudyIdentity { get; set; }
    
        public virtual DeliveryMethodType DeliveryMethodType { get; set; }
        public virtual EducationOrganization EducationOrganization { get; set; }
        public virtual InterventionClassType InterventionClassType { get; set; }
        public virtual InterventionPrescription InterventionPrescription { get; set; }
        public virtual ICollection<InterventionStudyAppropriateGradeLevel> InterventionStudyAppropriateGradeLevels { get; set; }
        public virtual ICollection<InterventionStudyAppropriateSex> InterventionStudyAppropriateSexes { get; set; }
        public virtual ICollection<InterventionStudyEducationContent> InterventionStudyEducationContents { get; set; }
        public virtual ICollection<InterventionStudyInterventionEffectiveness> InterventionStudyInterventionEffectivenesses { get; set; }
        public virtual ICollection<InterventionStudyLearningResourceMetadataURI> InterventionStudyLearningResourceMetadataURIs { get; set; }
        public virtual ICollection<InterventionStudyPopulationServed> InterventionStudyPopulationServeds { get; set; }
        public virtual ICollection<InterventionStudyStateAbbreviation> InterventionStudyStateAbbreviations { get; set; }
        public virtual ICollection<InterventionStudyURI> InterventionStudyURIs { get; set; }
    }
}
