//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageDescriptor
    {
        public int LanguageDescriptorId { get; set; }
        public Nullable<int> LanguageTypeId { get; set; }
    	public virtual LanguageType LanguageType { get; set; }
    }
}
