//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageDescriptor
    {
        public LanguageDescriptor()
        {
            this.AssessmentFamilyLanguages = new HashSet<AssessmentFamilyLanguage>();
            this.AssessmentLanguages = new HashSet<AssessmentLanguage>();
            this.EducationContentLanguages = new HashSet<EducationContentLanguage>();
            this.Sections = new HashSet<Section>();
            this.StaffLanguages = new HashSet<StaffLanguage>();
            this.StudentAssessments = new HashSet<StudentAssessment>();
            this.StudentLanguages = new HashSet<StudentLanguage>();
        }
    
        public int LanguageDescriptorId { get; set; }
        public Nullable<int> LanguageTypeId { get; set; }
    
        public virtual ICollection<AssessmentFamilyLanguage> AssessmentFamilyLanguages { get; set; }
        public virtual ICollection<AssessmentLanguage> AssessmentLanguages { get; set; }
        public virtual Descriptor Descriptor { get; set; }
        public virtual ICollection<EducationContentLanguage> EducationContentLanguages { get; set; }
        public virtual LanguageType LanguageType { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
        public virtual ICollection<StaffLanguage> StaffLanguages { get; set; }
        public virtual ICollection<StudentAssessment> StudentAssessments { get; set; }
        public virtual ICollection<StudentLanguage> StudentLanguages { get; set; }
    }
}
