//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningObjectiveContentStandardAuthor
    {
        public LearningObjectiveContentStandardAuthor()
        {
    		this.CreateDate = System.DateTime.Now;
        }
    
        public string Objective { get; set; }
        public int AcademicSubjectDescriptorId { get; set; }
        public int ObjectiveGradeLevelDescriptorId { get; set; }
        public string Author { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int LearningObjectiveContentStandardAuthorIdentity { get; set; }
    
        public virtual LearningObjectiveContentStandard LearningObjectiveContentStandard { get; set; }
    }
}
