//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LevelOfEducationDescriptor
    {
        public LevelOfEducationDescriptor()
        {
            this.Staffs = new HashSet<Staff>();
        }
    
        public int LevelOfEducationDescriptorId { get; set; }
        public Nullable<int> LevelOfEducationTypeId { get; set; }
    
        public virtual Descriptor Descriptor { get; set; }
        public virtual LevelOfEducationType LevelOfEducationType { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
    }
}
