//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalEducationAgencyFederalFund
    {
        public LocalEducationAgencyFederalFund()
        {
    		this.Id = System.Guid.NewGuid();
    		this.LastModifiedDate = System.DateTime.Now;
    		this.CreateDate = System.DateTime.Now;
        }
    
        public int LocalEducationAgencyId { get; set; }
        public int FiscalYear { get; set; }
        public Nullable<decimal> InnovativeDollarsSpent { get; set; }
        public Nullable<decimal> InnovativeDollarsSpentOnStrategicPriorities { get; set; }
        public Nullable<decimal> InnovativeProgramsFundsReceived { get; set; }
        public Nullable<decimal> SchoolImprovementAllocation { get; set; }
        public Nullable<decimal> SupplementalEducationalServicesFundsSpent { get; set; }
        public Nullable<decimal> SupplementalEducationalServicesPerPupilExpenditure { get; set; }
        public Nullable<decimal> SchoolImprovementReservedFundsPercentage { get; set; }
        public Nullable<decimal> StateAssessmentAdministrationFunding { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int LocalEducationAgencyFederalFundsIdentity { get; set; }
    
        public virtual LocalEducationAgency LocalEducationAgency { get; set; }
    }
}
