//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalEducationAgency
    {
        public LocalEducationAgency()
        {
            this.LocalEducationAgency1 = new HashSet<LocalEducationAgency>();
            this.LocalEducationAgencyAccountabilities = new HashSet<LocalEducationAgencyAccountability>();
            this.LocalEducationAgencyFederalFunds = new HashSet<LocalEducationAgencyFederalFund>();
            this.Schools = new HashSet<School>();
        }
    
        public int LocalEducationAgencyId { get; set; }
        public Nullable<int> ParentLocalEducationAgencyId { get; set; }
        public int LocalEducationAgencyCategoryTypeId { get; set; }
        public Nullable<int> CharterStatusTypeId { get; set; }
        public Nullable<int> EducationServiceCenterId { get; set; }
        public Nullable<int> StateEducationAgencyId { get; set; }
    
        public virtual CharterStatusType CharterStatusType { get; set; }
        public virtual EducationOrganization EducationOrganization { get; set; }
        public virtual EducationServiceCenter EducationServiceCenter { get; set; }
        public virtual ICollection<LocalEducationAgency> LocalEducationAgency1 { get; set; }
        public virtual LocalEducationAgency LocalEducationAgency2 { get; set; }
        public virtual LocalEducationAgencyCategoryType LocalEducationAgencyCategoryType { get; set; }
        public virtual StateEducationAgency StateEducationAgency { get; set; }
        public virtual ICollection<LocalEducationAgencyAccountability> LocalEducationAgencyAccountabilities { get; set; }
        public virtual ICollection<LocalEducationAgencyFederalFund> LocalEducationAgencyFederalFunds { get; set; }
        public virtual ICollection<School> Schools { get; set; }
    }
}
