//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenStaffPosition
    {
        public OpenStaffPosition()
        {
    		this.Id = System.Guid.NewGuid();
    		this.LastModifiedDate = System.DateTime.Now;
    		this.CreateDate = System.DateTime.Now;
            this.OpenStaffPositionAcademicSubjects = new HashSet<OpenStaffPositionAcademicSubject>();
            this.OpenStaffPositionInstructionalGradeLevels = new HashSet<OpenStaffPositionInstructionalGradeLevel>();
        }
    
        public int EducationOrganizationId { get; set; }
        public int EmploymentStatusDescriptorId { get; set; }
        public int StaffClassificationDescriptorId { get; set; }
        public string RequisitionNumber { get; set; }
        public System.DateTime DatePosted { get; set; }
        public string PositionTitle { get; set; }
        public Nullable<int> ProgramAssignmentDescriptorId { get; set; }
        public Nullable<System.DateTime> DatePostingRemoved { get; set; }
        public Nullable<int> PostingResultTypeId { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int OpenStaffPositionIdentity { get; set; }
    
        public virtual EducationOrganization EducationOrganization { get; set; }
        public virtual EmploymentStatusDescriptor EmploymentStatusDescriptor { get; set; }
        public virtual PostingResultType PostingResultType { get; set; }
        public virtual ProgramAssignmentDescriptor ProgramAssignmentDescriptor { get; set; }
        public virtual StaffClassificationDescriptor StaffClassificationDescriptor { get; set; }
        public virtual ICollection<OpenStaffPositionAcademicSubject> OpenStaffPositionAcademicSubjects { get; set; }
        public virtual ICollection<OpenStaffPositionInstructionalGradeLevel> OpenStaffPositionInstructionalGradeLevels { get; set; }
    }
}
