//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentTelephone
    {
        public ParentTelephone()
        {
    		this.CreateDate = System.DateTime.Now;
        }
    
        public int ParentUSI { get; set; }
        public int TelephoneNumberTypeId { get; set; }
        public Nullable<int> OrderOfPriority { get; set; }
        public Nullable<bool> TextMessageCapabilityIndicator { get; set; }
        public string TelephoneNumber { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int ParentTelephoneIdentity { get; set; }
    
        public virtual Parent Parent { get; set; }
        public virtual TelephoneNumberType TelephoneNumberType { get; set; }
    }
}
