//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramAssignmentDescriptor
    {
        public ProgramAssignmentDescriptor()
        {
            this.OpenStaffPositions = new HashSet<OpenStaffPosition>();
            this.StaffSchoolAssociations = new HashSet<StaffSchoolAssociation>();
        }
    
        public int ProgramAssignmentDescriptorId { get; set; }
        public Nullable<int> ProgramAssignmentTypeId { get; set; }
    
        public virtual Descriptor Descriptor { get; set; }
        public virtual ICollection<OpenStaffPosition> OpenStaffPositions { get; set; }
        public virtual ProgramAssignmentType ProgramAssignmentType { get; set; }
        public virtual ICollection<StaffSchoolAssociation> StaffSchoolAssociations { get; set; }
    }
}
