//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicationStatusType
    {
        public PublicationStatusType()
        {
            this.AssessmentContentStandards = new HashSet<AssessmentContentStandard>();
            this.AssessmentFamilyContentStandards = new HashSet<AssessmentFamilyContentStandard>();
            this.LearningObjectiveContentStandards = new HashSet<LearningObjectiveContentStandard>();
            this.LearningStandardContentStandards = new HashSet<LearningStandardContentStandard>();
        }
    
        public int PublicationStatusTypeId { get; set; }
        public string CodeValue { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ICollection<AssessmentContentStandard> AssessmentContentStandards { get; set; }
        public virtual ICollection<AssessmentFamilyContentStandard> AssessmentFamilyContentStandards { get; set; }
        public virtual ICollection<LearningObjectiveContentStandard> LearningObjectiveContentStandards { get; set; }
        public virtual ICollection<LearningStandardContentStandard> LearningStandardContentStandards { get; set; }
    }
}
