//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReasonExitedDescriptor
    {
        public ReasonExitedDescriptor()
        {
            this.StudentProgramAssociations = new HashSet<StudentProgramAssociation>();
        }
    
        public int ReasonExitedDescriptorId { get; set; }
        public Nullable<int> ReasonExitedTypeId { get; set; }
    
        public virtual Descriptor Descriptor { get; set; }
        public virtual ReasonExitedType ReasonExitedType { get; set; }
        public virtual ICollection<StudentProgramAssociation> StudentProgramAssociations { get; set; }
    }
}
