//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReporterDescriptionDescriptor
    {
        public ReporterDescriptionDescriptor()
        {
            this.DisciplineIncidents = new HashSet<DisciplineIncident>();
        }
    
        public int ReporterDescriptionDescriptorId { get; set; }
        public Nullable<int> ReporterDescriptionTypeId { get; set; }
    
        public virtual Descriptor Descriptor { get; set; }
        public virtual ICollection<DisciplineIncident> DisciplineIncidents { get; set; }
        public virtual ReporterDescriptionType ReporterDescriptionType { get; set; }
    }
}
