//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportCard
    {
        public ReportCard()
        {
            this.ReportCardGrades = new HashSet<ReportCardGrade>();
            this.ReportCardStudentCompetencyObjectives = new HashSet<ReportCardStudentCompetencyObjective>();
            this.ReportCardStudentLearningObjectives = new HashSet<ReportCardStudentLearningObjective>();
            this.StudentAcademicRecordReportCards = new HashSet<StudentAcademicRecordReportCard>();
        }
    
        public int StudentUSI { get; set; }
        public int GradingPeriodEducationOrganizationId { get; set; }
        public int GradingPeriodDescriptorId { get; set; }
        public System.DateTime GradingPeriodBeginDate { get; set; }
        public Nullable<decimal> GPAGivenGradingPeriod { get; set; }
        public Nullable<decimal> GPACumulative { get; set; }
        public Nullable<decimal> NumberOfDaysAbsent { get; set; }
        public Nullable<decimal> NumberOfDaysInAttendance { get; set; }
        public Nullable<int> NumberOfDaysTardy { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual GradingPeriod GradingPeriod { get; set; }
        public virtual Student Student { get; set; }
        public virtual ICollection<ReportCardGrade> ReportCardGrades { get; set; }
        public virtual ICollection<ReportCardStudentCompetencyObjective> ReportCardStudentCompetencyObjectives { get; set; }
        public virtual ICollection<ReportCardStudentLearningObjective> ReportCardStudentLearningObjectives { get; set; }
        public virtual ICollection<StudentAcademicRecordReportCard> StudentAcademicRecordReportCards { get; set; }
    }
}
