//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponsibilityDescriptor
    {
        public ResponsibilityDescriptor()
        {
            this.StudentEducationOrganizationAssociations = new HashSet<StudentEducationOrganizationAssociation>();
        }
    
        public int ResponsibilityDescriptorId { get; set; }
        public Nullable<int> ResponsibilityTypeId { get; set; }
    
        public virtual Descriptor Descriptor { get; set; }
        public virtual ResponsibilityType ResponsibilityType { get; set; }
        public virtual ICollection<StudentEducationOrganizationAssociation> StudentEducationOrganizationAssociations { get; set; }
    }
}
