//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolYearType
    {
        public SchoolYearType()
        {
    		this.Id = System.Guid.NewGuid();
    		this.LastModifiedDate = System.DateTime.Now;
    		this.CreateDate = System.DateTime.Now;
            this.AccountabilityRatings = new HashSet<AccountabilityRating>();
            this.GraduationPlans = new HashSet<GraduationPlan>();
            this.LocalEducationAgencyAccountabilities = new HashSet<LocalEducationAgencyAccountability>();
            this.Sessions = new HashSet<Session>();
            this.StateEducationAgencyAccountabilities = new HashSet<StateEducationAgencyAccountability>();
            this.StudentAcademicRecords = new HashSet<StudentAcademicRecord>();
            this.StudentCohortYears = new HashSet<StudentCohortYear>();
            this.StudentSchoolAssociations = new HashSet<StudentSchoolAssociation>();
            this.StudentSchoolAssociations1 = new HashSet<StudentSchoolAssociation>();
        }
    
        public short SchoolYear { get; set; }
        public string SchoolYearDescription { get; set; }
        public bool CurrentSchoolYear { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ICollection<AccountabilityRating> AccountabilityRatings { get; set; }
        public virtual ICollection<GraduationPlan> GraduationPlans { get; set; }
        public virtual ICollection<LocalEducationAgencyAccountability> LocalEducationAgencyAccountabilities { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
        public virtual ICollection<StateEducationAgencyAccountability> StateEducationAgencyAccountabilities { get; set; }
        public virtual ICollection<StudentAcademicRecord> StudentAcademicRecords { get; set; }
        public virtual ICollection<StudentCohortYear> StudentCohortYears { get; set; }
        public virtual ICollection<StudentSchoolAssociation> StudentSchoolAssociations { get; set; }
        public virtual ICollection<StudentSchoolAssociation> StudentSchoolAssociations1 { get; set; }
    }
}
