//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.BellSchedules = new HashSet<BellSchedule>();
            this.CourseOfferings = new HashSet<CourseOffering>();
            this.DisciplineActions = new HashSet<DisciplineAction>();
            this.DisciplineActions1 = new HashSet<DisciplineAction>();
            this.DisciplineIncidents = new HashSet<DisciplineIncident>();
            this.FeederSchoolAssociations = new HashSet<FeederSchoolAssociation>();
            this.FeederSchoolAssociations1 = new HashSet<FeederSchoolAssociation>();
            this.Locations = new HashSet<Location>();
            this.RestraintEvents = new HashSet<RestraintEvent>();
            this.SchoolCategories = new HashSet<SchoolCategory>();
            this.SchoolGradeLevels = new HashSet<SchoolGradeLevel>();
            this.Sections = new HashSet<Section>();
            this.Sessions = new HashSet<Session>();
            this.StaffSchoolAssociations = new HashSet<StaffSchoolAssociation>();
            this.StudentSchoolAssociations = new HashSet<StudentSchoolAssociation>();
            this.StudentSchoolAttendanceEvents = new HashSet<StudentSchoolAttendanceEvent>();
        }
    
        public int SchoolId { get; set; }
        public Nullable<int> LocalEducationAgencyId { get; set; }
        public Nullable<int> SchoolTypeId { get; set; }
        public Nullable<int> CharterStatusTypeId { get; set; }
        public Nullable<int> TitleIPartASchoolDesignationTypeId { get; set; }
        public Nullable<int> MagnetSpecialProgramEmphasisSchoolTypeId { get; set; }
        public Nullable<int> AdministrativeFundingControlDescriptorId { get; set; }
        public Nullable<int> InternetAccessTypeId { get; set; }
        public int SchoolIdentity { get; set; }
    
        public virtual AdministrativeFundingControlDescriptor AdministrativeFundingControlDescriptor { get; set; }
        public virtual ICollection<BellSchedule> BellSchedules { get; set; }
        public virtual CharterStatusType CharterStatusType { get; set; }
        public virtual ICollection<CourseOffering> CourseOfferings { get; set; }
        public virtual ICollection<DisciplineAction> DisciplineActions { get; set; }
        public virtual ICollection<DisciplineAction> DisciplineActions1 { get; set; }
        public virtual ICollection<DisciplineIncident> DisciplineIncidents { get; set; }
        public virtual EducationOrganization EducationOrganization { get; set; }
        public virtual ICollection<FeederSchoolAssociation> FeederSchoolAssociations { get; set; }
        public virtual ICollection<FeederSchoolAssociation> FeederSchoolAssociations1 { get; set; }
        public virtual InternetAccessType InternetAccessType { get; set; }
        public virtual LocalEducationAgency LocalEducationAgency { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual MagnetSpecialProgramEmphasisSchoolType MagnetSpecialProgramEmphasisSchoolType { get; set; }
        public virtual ICollection<RestraintEvent> RestraintEvents { get; set; }
        public virtual SchoolType SchoolType { get; set; }
        public virtual TitleIPartASchoolDesignationType TitleIPartASchoolDesignationType { get; set; }
        public virtual ICollection<SchoolCategory> SchoolCategories { get; set; }
        public virtual ICollection<SchoolGradeLevel> SchoolGradeLevels { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
        public virtual ICollection<StaffSchoolAssociation> StaffSchoolAssociations { get; set; }
        public virtual ICollection<StudentSchoolAssociation> StudentSchoolAssociations { get; set; }
        public virtual ICollection<StudentSchoolAttendanceEvent> StudentSchoolAttendanceEvents { get; set; }
    }
}
