//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceDescriptor
    {
        public ServiceDescriptor()
        {
            this.ProgramServices = new HashSet<ProgramService>();
            this.StudentProgramAssociationServices = new HashSet<StudentProgramAssociationService>();
        }
    
        public int ServiceDescriptorId { get; set; }
        public string ServiceCategory { get; set; }
    
        public virtual Descriptor Descriptor { get; set; }
        public virtual ICollection<ProgramService> ProgramServices { get; set; }
        public virtual ICollection<StudentProgramAssociationService> StudentProgramAssociationServices { get; set; }
    }
}
