//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionGradingPeriod
    {
        public SessionGradingPeriod()
        {
    		this.CreateDate = System.DateTime.Now;
        }
    
        public int EducationOrganizationId { get; set; }
        public int TermTypeId { get; set; }
        public short SchoolYear { get; set; }
        public int GradingPeriodDescriptorId { get; set; }
        public System.DateTime BeginDate { get; set; }
        public int SchoolId { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual GradingPeriod GradingPeriod { get; set; }
        public virtual Session Session { get; set; }
    }
}
