//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SexType
    {
        public SexType()
        {
    		this.Id = System.Guid.NewGuid();
    		this.LastModifiedDate = System.DateTime.Now;
    		this.CreateDate = System.DateTime.Now;
            this.EducationContentAppropriateSexes = new HashSet<EducationContentAppropriateSex>();
            this.InterventionAppropriateSexes = new HashSet<InterventionAppropriateSex>();
            this.InterventionPrescriptionAppropriateSexes = new HashSet<InterventionPrescriptionAppropriateSex>();
            this.InterventionStudyAppropriateSexes = new HashSet<InterventionStudyAppropriateSex>();
            this.Parents = new HashSet<Parent>();
            this.Staffs = new HashSet<Staff>();
            this.Students = new HashSet<Student>();
        }
    
        public int SexTypeId { get; set; }
        public string CodeValue { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ICollection<EducationContentAppropriateSex> EducationContentAppropriateSexes { get; set; }
        public virtual ICollection<InterventionAppropriateSex> InterventionAppropriateSexes { get; set; }
        public virtual ICollection<InterventionPrescriptionAppropriateSex> InterventionPrescriptionAppropriateSexes { get; set; }
        public virtual ICollection<InterventionStudyAppropriateSex> InterventionStudyAppropriateSexes { get; set; }
        public virtual ICollection<Parent> Parents { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
