//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffCredential
    {
        public int StaffUSI { get; set; }
        public int CredentialFieldDescriptorId { get; set; }
        public int CredentialTypeId { get; set; }
        public int LevelDescriptorId { get; set; }
        public int TeachingCredentialDescriptorId { get; set; }
        public System.DateTime CredentialIssuanceDate { get; set; }
        public Nullable<System.DateTime> CredentialExpirationDate { get; set; }
        public Nullable<int> TeachingCredentialBasisTypeId { get; set; }
        public Nullable<int> StateOfIssueStateAbbreviationTypeId { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual CredentialFieldDescriptor CredentialFieldDescriptor { get; set; }
        public virtual CredentialType CredentialType { get; set; }
        public virtual LevelDescriptor LevelDescriptor { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual StateAbbreviationType StateAbbreviationType { get; set; }
        public virtual TeachingCredentialBasisType TeachingCredentialBasisType { get; set; }
        public virtual TeachingCredentialDescriptor TeachingCredentialDescriptor { get; set; }
    }
}
