//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffEducationOrganizationAssignmentAssociation
    {
        public int StaffUSI { get; set; }
        public int EducationOrganizationId { get; set; }
        public int StaffClassificationDescriptorId { get; set; }
        public System.DateTime BeginDate { get; set; }
        public string PositionTitle { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> OrderOfAssignment { get; set; }
        public Nullable<int> EmploymentEducationOrganizationId { get; set; }
        public Nullable<int> EmploymentStatusDescriptorId { get; set; }
        public Nullable<System.DateTime> EmploymentHireDate { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual EducationOrganization EducationOrganization { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual StaffClassificationDescriptor StaffClassificationDescriptor { get; set; }
        public virtual StaffEducationOrganizationEmploymentAssociation StaffEducationOrganizationEmploymentAssociation { get; set; }
    }
}
