//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffClassificationDescriptor
    {
        public StaffClassificationDescriptor()
        {
            this.OpenStaffPositions = new HashSet<OpenStaffPosition>();
            this.StaffEducationOrganizationAssignmentAssociations = new HashSet<StaffEducationOrganizationAssignmentAssociation>();
        }
    
        public int StaffClassificationDescriptorId { get; set; }
        public Nullable<int> StaffClassificationTypeId { get; set; }
    
        public virtual Descriptor Descriptor { get; set; }
        public virtual ICollection<OpenStaffPosition> OpenStaffPositions { get; set; }
        public virtual StaffClassificationType StaffClassificationType { get; set; }
        public virtual ICollection<StaffEducationOrganizationAssignmentAssociation> StaffEducationOrganizationAssignmentAssociations { get; set; }
    }
}
