//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateAbbreviationType
    {
        public StateAbbreviationType()
        {
            this.EducationOrganizationAddresses = new HashSet<EducationOrganizationAddress>();
            this.InterventionStudyStateAbbreviations = new HashSet<InterventionStudyStateAbbreviation>();
            this.ParentAddresses = new HashSet<ParentAddress>();
            this.StaffAddresses = new HashSet<StaffAddress>();
            this.StaffCredentials = new HashSet<StaffCredential>();
            this.Students = new HashSet<Student>();
            this.StudentAddresses = new HashSet<StudentAddress>();
        }
    
        public int StateAbbreviationTypeId { get; set; }
        public string CodeValue { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ICollection<EducationOrganizationAddress> EducationOrganizationAddresses { get; set; }
        public virtual ICollection<InterventionStudyStateAbbreviation> InterventionStudyStateAbbreviations { get; set; }
        public virtual ICollection<ParentAddress> ParentAddresses { get; set; }
        public virtual ICollection<StaffAddress> StaffAddresses { get; set; }
        public virtual ICollection<StaffCredential> StaffCredentials { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<StudentAddress> StudentAddresses { get; set; }
    }
}
