//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateEducationAgency
    {
        public StateEducationAgency()
        {
            this.EducationServiceCenters = new HashSet<EducationServiceCenter>();
            this.LocalEducationAgencies = new HashSet<LocalEducationAgency>();
            this.StateEducationAgencyAccountabilities = new HashSet<StateEducationAgencyAccountability>();
            this.StateEducationAgencyFederalFunds = new HashSet<StateEducationAgencyFederalFund>();
        }
    
        public int StateEducationAgencyId { get; set; }
    
        public virtual EducationOrganization EducationOrganization { get; set; }
        public virtual ICollection<EducationServiceCenter> EducationServiceCenters { get; set; }
        public virtual ICollection<LocalEducationAgency> LocalEducationAgencies { get; set; }
        public virtual ICollection<StateEducationAgencyAccountability> StateEducationAgencyAccountabilities { get; set; }
        public virtual ICollection<StateEducationAgencyFederalFund> StateEducationAgencyFederalFunds { get; set; }
    }
}
