//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentParentAssociation
    {
        public StudentParentAssociation()
        {
    		this.Id = System.Guid.NewGuid();
    		this.LastModifiedDate = System.DateTime.Now;
    		this.CreateDate = System.DateTime.Now;
        }
    
        public int StudentUSI { get; set; }
        public int ParentUSI { get; set; }
        public int RelationTypeId { get; set; }
        public Nullable<bool> PrimaryContactStatus { get; set; }
        public Nullable<bool> LivesWith { get; set; }
        public Nullable<bool> EmergencyContactStatus { get; set; }
        public Nullable<int> ContactPriority { get; set; }
        public string ContactRestrictions { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int StudentParentAssociationIdentity { get; set; }
    
        public virtual Parent Parent { get; set; }
        public virtual RelationType RelationType { get; set; }
        public virtual Student Student { get; set; }
    }
}
