//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCharacteristicDescriptor
    {
        public StudentCharacteristicDescriptor()
        {
            this.StudentCharacteristics = new HashSet<StudentCharacteristic>();
        }
    
        public int StudentCharacteristicDescriptorId { get; set; }
        public Nullable<int> StudentCharacteristicTypeId { get; set; }
    
        public virtual Descriptor Descriptor { get; set; }
        public virtual ICollection<StudentCharacteristic> StudentCharacteristics { get; set; }
        public virtual StudentCharacteristicType StudentCharacteristicType { get; set; }
    }
}
