//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAcademicDetail
    {
        public StudentAcademicDetail()
        {
    		this.Id = System.Guid.NewGuid();
    		this.LastModifiedDate = System.DateTime.Now;
    		this.CreateDate = System.DateTime.Now;
        }
    
        public int StudentUSI { get; set; }
        public decimal ReadingScore { get; set; }
        public decimal WritingScore { get; set; }
        public decimal MathScore { get; set; }
        public short SchoolYear { get; set; }
        public int GradeLevelTypeId { get; set; }
        public string PerfomanceHistory { get; set; }
        public string PerformanceHistoryFileUrl { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual GradeLevelType GradeLevelType { get; set; }
        public virtual SchoolYearType SchoolYearType { get; set; }
        public virtual Student Student { get; set; }
    }
}
