//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAcademicRecordReportCard
    {
        public StudentAcademicRecordReportCard()
        {
    		this.CreateDate = System.DateTime.Now;
        }
    
        public int StudentUSI { get; set; }
        public int EducationOrganizationId { get; set; }
        public short SchoolYear { get; set; }
        public int TermTypeId { get; set; }
        public int GradingPeriodEducationOrganizationId { get; set; }
        public int GradingPeriodDescriptorId { get; set; }
        public System.DateTime GradingPeriodBeginDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ReportCard ReportCard { get; set; }
        public virtual StudentAcademicRecord StudentAcademicRecord { get; set; }
    }
}
