//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAssessmentStudentObjectiveAssessment
    {
        public StudentAssessmentStudentObjectiveAssessment()
        {
    		this.CreateDate = System.DateTime.Now;
            this.StudentAssessmentStudentObjectiveAssessmentPerformanceLevels = new HashSet<StudentAssessmentStudentObjectiveAssessmentPerformanceLevel>();
            this.StudentAssessmentStudentObjectiveAssessmentScoreResults = new HashSet<StudentAssessmentStudentObjectiveAssessmentScoreResult>();
        }
    
        public int StudentUSI { get; set; }
        public string AssessmentTitle { get; set; }
        public int AcademicSubjectDescriptorId { get; set; }
        public int AssessedGradeLevelDescriptorId { get; set; }
        public int Version { get; set; }
        public string IdentificationCode { get; set; }
        public System.DateTime AdministrationDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ObjectiveAssessment ObjectiveAssessment { get; set; }
        public virtual StudentAssessment StudentAssessment { get; set; }
        public virtual ICollection<StudentAssessmentStudentObjectiveAssessmentPerformanceLevel> StudentAssessmentStudentObjectiveAssessmentPerformanceLevels { get; set; }
        public virtual ICollection<StudentAssessmentStudentObjectiveAssessmentScoreResult> StudentAssessmentStudentObjectiveAssessmentScoreResults { get; set; }
    }
}
