//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDisciplineIncidentAssociation
    {
        public StudentDisciplineIncidentAssociation()
        {
    		this.Id = System.Guid.NewGuid();
    		this.LastModifiedDate = System.DateTime.Now;
    		this.CreateDate = System.DateTime.Now;
            this.StudentDisciplineIncidentAssociationBehaviors = new HashSet<StudentDisciplineIncidentAssociationBehavior>();
        }
    
        public int StudentUSI { get; set; }
        public int SchoolId { get; set; }
        public string IncidentIdentifier { get; set; }
        public int StudentParticipationCodeTypeId { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int StudentDisciplineIncidentAssociationIdentity { get; set; }
    
        public virtual DisciplineIncident DisciplineIncident { get; set; }
        public virtual Student Student { get; set; }
        public virtual StudentParticipationCodeType StudentParticipationCodeType { get; set; }
        public virtual ICollection<StudentDisciplineIncidentAssociationBehavior> StudentDisciplineIncidentAssociationBehaviors { get; set; }
    }
}
