//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSchoolAssociationEducationPlan
    {
        public StudentSchoolAssociationEducationPlan()
        {
    		this.CreateDate = System.DateTime.Now;
        }
    
        public int StudentUSI { get; set; }
        public int SchoolId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int EducationPlanTypeId { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual EducationPlanType EducationPlanType { get; set; }
        public virtual StudentSchoolAssociation StudentSchoolAssociation { get; set; }
    }
}
