//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCohortAssociation
    {
        public StudentCohortAssociation()
        {
    		this.Id = System.Guid.NewGuid();
    		this.LastModifiedDate = System.DateTime.Now;
    		this.CreateDate = System.DateTime.Now;
            this.StudentCohortAssociationSections = new HashSet<StudentCohortAssociationSection>();
        }
    
        public int StudentUSI { get; set; }
        public int EducationOrganizationId { get; set; }
        public string CohortIdentifier { get; set; }
        public System.DateTime BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int StudentCohortAssociationIdentity { get; set; }
    
        public virtual Cohort Cohort { get; set; }
        public virtual Student Student { get; set; }
        public virtual ICollection<StudentCohortAssociationSection> StudentCohortAssociationSections { get; set; }
    }
}
