//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentLanguage
    {
        public StudentLanguage()
        {
            this.StudentLanguageUses = new HashSet<StudentLanguageUse>();
        }
    
        public int StudentUSI { get; set; }
        public int LanguageDescriptorId { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual LanguageDescriptor LanguageDescriptor { get; set; }
        public virtual Student Student { get; set; }
        public virtual ICollection<StudentLanguageUse> StudentLanguageUses { get; set; }
    }
}
