//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentGradebookEntry
    {
        public StudentGradebookEntry()
        {
    		this.Id = System.Guid.NewGuid();
    		this.LastModifiedDate = System.DateTime.Now;
    		this.CreateDate = System.DateTime.Now;
        }
    
        public int StudentUSI { get; set; }
        public int SchoolId { get; set; }
        public string ClassPeriodName { get; set; }
        public string ClassroomIdentificationCode { get; set; }
        public string LocalCourseCode { get; set; }
        public int TermTypeId { get; set; }
        public short SchoolYear { get; set; }
        public System.DateTime BeginDate { get; set; }
        public string GradebookEntryTitle { get; set; }
        public System.DateTime DateAssigned { get; set; }
        public Nullable<System.DateTime> DateFulfilled { get; set; }
        public string LetterGradeEarned { get; set; }
        public Nullable<int> NumericGradeEarned { get; set; }
        public Nullable<int> CompetencyLevelDescriptorId { get; set; }
        public string DiagnosticStatement { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int StudentGradebookEntryIdentity { get; set; }
    
        public virtual CompetencyLevelDescriptor CompetencyLevelDescriptor { get; set; }
        public virtual GradebookEntry GradebookEntry { get; set; }
        public virtual StudentSectionAssociation StudentSectionAssociation { get; set; }
    }
}
