//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentLearningStyle
    {
        public StudentLearningStyle()
        {
    		this.CreateDate = System.DateTime.Now;
        }
    
        public int StudentUSI { get; set; }
        public decimal VisualLearning { get; set; }
        public decimal AuditoryLearning { get; set; }
        public decimal TactileLearning { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int StudentLearningStyleIdentity { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
