//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInterventionAssociationInterventionEffectiveness
    {
        public StudentInterventionAssociationInterventionEffectiveness()
        {
    		this.CreateDate = System.DateTime.Now;
        }
    
        public int StudentUSI { get; set; }
        public string InterventionIdentificationCode { get; set; }
        public int InterventionEducationOrganizationId { get; set; }
        public int DiagnosisDescriptorId { get; set; }
        public int PopulationServedTypeId { get; set; }
        public int GradeLevelDescriptorId { get; set; }
        public Nullable<int> ImprovementIndex { get; set; }
        public int InterventionEffectivenessRatingTypeId { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual DiagnosisDescriptor DiagnosisDescriptor { get; set; }
        public virtual GradeLevelDescriptor GradeLevelDescriptor { get; set; }
        public virtual InterventionEffectivenessRatingType InterventionEffectivenessRatingType { get; set; }
        public virtual PopulationServedType PopulationServedType { get; set; }
        public virtual StudentInterventionAssociation StudentInterventionAssociation { get; set; }
    }
}
