//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentProgramParticipation
    {
        public StudentProgramParticipation()
        {
    		this.CreateDate = System.DateTime.Now;
            this.StudentProgramParticipationProgramCharacteristics = new HashSet<StudentProgramParticipationProgramCharacteristic>();
        }
    
        public int StudentUSI { get; set; }
        public int ProgramTypeId { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string DesignatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ProgramType ProgramType { get; set; }
        public virtual Student Student { get; set; }
        public virtual ICollection<StudentProgramParticipationProgramCharacteristic> StudentProgramParticipationProgramCharacteristics { get; set; }
    }
}
