//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersionLevel
    {
        public VersionLevel()
        {
        }
    
        public string ScriptSource { get; set; }
        public string ScriptType { get; set; }
        public string DatabaseType { get; set; }
        public string SubType { get; set; }
        public int VersionLevel1 { get; set; }
    }
}
