//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Web.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeaponDescriptor
    {
        public WeaponDescriptor()
        {
            this.DisciplineIncidentWeapons = new HashSet<DisciplineIncidentWeapon>();
        }
    
        public int WeaponDescriptorId { get; set; }
        public Nullable<int> WeaponTypeId { get; set; }
    
        public virtual Descriptor Descriptor { get; set; }
        public virtual ICollection<DisciplineIncidentWeapon> DisciplineIncidentWeapons { get; set; }
        public virtual WeaponType WeaponType { get; set; }
    }
}
