// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace NGL.Web.Controllers
{
    public partial class ScheduleController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ScheduleController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Set()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Set);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult RemoveStudent()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.RemoveStudent);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ScheduleStudent()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ScheduleStudent);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetSections()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetSections);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ScheduleController Actions { get { return MVC.Schedule; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Schedule";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Schedule";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Set = "Set";
            public readonly string RemoveStudent = "RemoveStudent";
            public readonly string ScheduleStudent = "ScheduleStudent";
            public readonly string GetSections = "GetSections";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Set = "Set";
            public const string RemoveStudent = "RemoveStudent";
            public const string ScheduleStudent = "ScheduleStudent";
            public const string GetSections = "GetSections";
        }


        static readonly ActionParamsClass_Set s_params_Set = new ActionParamsClass_Set();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Set SetParams { get { return s_params_Set; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Set
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_RemoveStudent s_params_RemoveStudent = new ActionParamsClass_RemoveStudent();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RemoveStudent RemoveStudentParams { get { return s_params_RemoveStudent; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RemoveStudent
        {
            public readonly string studentSectionId = "studentSectionId";
        }
        static readonly ActionParamsClass_ScheduleStudent s_params_ScheduleStudent = new ActionParamsClass_ScheduleStudent();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ScheduleStudent ScheduleStudentParams { get { return s_params_ScheduleStudent; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ScheduleStudent
        {
            public readonly string setModel = "setModel";
        }
        static readonly ActionParamsClass_GetSections s_params_GetSections = new ActionParamsClass_GetSections();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetSections GetSectionsParams { get { return s_params_GetSections; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetSections
        {
            public readonly string searchString = "searchString";
            public readonly string sessionId = "sessionId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Set = "Set";
            }
            public readonly string Set = "~/Views/Schedule/Set.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ScheduleController : NGL.Web.Controllers.ScheduleController
    {
        public T4MVC_ScheduleController() : base(Dummy.Instance) { }

        [NonAction]
        partial void SetOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Set(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Set);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            SetOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void RemoveStudentOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int studentSectionId);

        [NonAction]
        public override System.Web.Mvc.JsonResult RemoveStudent(int studentSectionId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.RemoveStudent);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "studentSectionId", studentSectionId);
            RemoveStudentOverride(callInfo, studentSectionId);
            return callInfo;
        }

        [NonAction]
        partial void ScheduleStudentOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, NGL.Web.Models.Schedule.SetModel setModel);

        [NonAction]
        public override System.Web.Mvc.JsonResult ScheduleStudent(NGL.Web.Models.Schedule.SetModel setModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ScheduleStudent);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "setModel", setModel);
            ScheduleStudentOverride(callInfo, setModel);
            return callInfo;
        }

        [NonAction]
        partial void GetSectionsOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string searchString, int sessionId);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetSections(string searchString, int sessionId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetSections);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchString", searchString);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sessionId", sessionId);
            GetSectionsOverride(callInfo, searchString, sessionId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
